# RUNNING: python -m src

# Event API which will be scraped
#  - user's activity: https://api.github.com/users/USERNAME/events
#  - organization's activity: https://api.github.com/orgs/ORG/events
#  - repo's activity: https://api.github.com/repos/USERNAME/REPO/events
# e.g. https://api.github.com/repos/valvesoftware/source-sdk-2013/events
EVENT_API = 'https://api.github.com/repos/valvesoftware/source-sdk-2013/events'

# Wait time between fetches. Might be overriden by GitHub
POLL_INTERVAL = 300

# GitHub API token (https://github.com/settings/personal-access-tokens)
GH_TOKEN = ''

# Discord Webhook. Generated in Channel -> Channel settings -> Connections -> Webhooks
DISCORD_WEBHOOK = 'https://discord.com/api/webhooks/123/456/github'

# Blacklisted repositories, e.g. "source-sdk-2013"
REPO_BLACKLIST = [ ]

# Blacklisted events, e.g. "watch"
#  - commit_comment -> comment on a commit
#  - create -> branch or tag created
#  - delete -> branch or tag deleted
#  - discussion -> discussion opened/edited/closed
#  - fork -> repo forked
#  - gollum -> wiki page created or updated
#  - issue_comment -> comment on an issue or PR
#  - issues -> issue opened/closed/edited/etc.
#  - member -> collaborator added to the repo
#  - public -> repo made public
#  - pull_request -> PR opened/closed/merged/reopened/etc.
#  - pull_request_review -> PR review submitted
#  - pull_request_review_comment -> comment on a PR's diff
#  - push -> commits pushed to a branch
#  - release -> release published
#  - watch -> repo starred
# Multiple values are specified like: ["issues", "watch"]
EVENT_BLACKLIST = [ ]

# Whitelisted users, e.g. "lilmayu" (the login username seen in URLs! not the display name)
USER_WHITELIST = [ ]

# If initial events should be skipped when running this script for the first time. Defaults to true.
SKIP_INITIAL_EVENTS = true
